a = input('digite algo: ')
print('O tipo primitivo desse valor e', type(a))
print('So tem espacos?', a.isspace())
print('e um numero?', a.isnumeric())
print('e alfabetico?', a.isalpha())
print('e alfanumerico?', a.isalnum())
print('esta em maiusuculas?', a.isupper())
print('esta em minusculas?', a.islower())
print('esta captalizada?', a.istitle())